on: push

name: Continuous integration

jobs:
  check:
    name: Lint, Check, Clippy, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: rustup component add rustfmt clippy

      - run: cargo fmt --all -- --check
      - run: cargo check
      - run: cargo clippy --version
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - run: cargo build
