on: [push, pull_request]

name: Continuous integration

jobs:
  ci:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup component add rustfmt
      - run: rustup component add clippy

      - name: rust fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
